// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package hello

import (
	"context"
	"fmt"
)

type HelloRequest struct {
	Name string `thrift:"name,1" frugal:"1,default,string" json:"name"`
}

func NewHelloRequest() *HelloRequest {
	return &HelloRequest{}
}

func (p *HelloRequest) InitDefault() {
}

func (p *HelloRequest) GetName() (v string) {
	return p.Name
}
func (p *HelloRequest) SetName(val string) {
	p.Name = val
}

func (p *HelloRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HelloRequest(%+v)", *p)
}

var fieldIDToName_HelloRequest = map[int16]string{
	1: "name",
}

type HelloResponse struct {
	Message string `thrift:"message,1" frugal:"1,default,string" json:"message"`
}

func NewHelloResponse() *HelloResponse {
	return &HelloResponse{}
}

func (p *HelloResponse) InitDefault() {
}

func (p *HelloResponse) GetMessage() (v string) {
	return p.Message
}
func (p *HelloResponse) SetMessage(val string) {
	p.Message = val
}

func (p *HelloResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HelloResponse(%+v)", *p)
}

var fieldIDToName_HelloResponse = map[int16]string{
	1: "message",
}

type HelloService interface {
	Hello(ctx context.Context, req *HelloRequest) (r *HelloResponse, err error)
}

type HelloServiceHelloArgs struct {
	Req *HelloRequest `thrift:"req,1" frugal:"1,default,HelloRequest" json:"req"`
}

func NewHelloServiceHelloArgs() *HelloServiceHelloArgs {
	return &HelloServiceHelloArgs{}
}

func (p *HelloServiceHelloArgs) InitDefault() {
}

var HelloServiceHelloArgs_Req_DEFAULT *HelloRequest

func (p *HelloServiceHelloArgs) GetReq() (v *HelloRequest) {
	if !p.IsSetReq() {
		return HelloServiceHelloArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *HelloServiceHelloArgs) SetReq(val *HelloRequest) {
	p.Req = val
}

func (p *HelloServiceHelloArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HelloServiceHelloArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HelloServiceHelloArgs(%+v)", *p)
}

var fieldIDToName_HelloServiceHelloArgs = map[int16]string{
	1: "req",
}

type HelloServiceHelloResult struct {
	Success *HelloResponse `thrift:"success,0,optional" frugal:"0,optional,HelloResponse" json:"success,omitempty"`
}

func NewHelloServiceHelloResult() *HelloServiceHelloResult {
	return &HelloServiceHelloResult{}
}

func (p *HelloServiceHelloResult) InitDefault() {
}

var HelloServiceHelloResult_Success_DEFAULT *HelloResponse

func (p *HelloServiceHelloResult) GetSuccess() (v *HelloResponse) {
	if !p.IsSetSuccess() {
		return HelloServiceHelloResult_Success_DEFAULT
	}
	return p.Success
}
func (p *HelloServiceHelloResult) SetSuccess(x interface{}) {
	p.Success = x.(*HelloResponse)
}

func (p *HelloServiceHelloResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HelloServiceHelloResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HelloServiceHelloResult(%+v)", *p)
}

var fieldIDToName_HelloServiceHelloResult = map[int16]string{
	0: "success",
}
